### ISSUE TITLE
Coordinate w/Auryn on how to put these repositories in a single one (used submodule for speed)

### ISSUE THREAD

**Issue by jjperezaguinaga** [ETHPoster/app#10]

**Comment by auryn-macmillan** [comment]
I think we should keep the contract as a separate repository. One of the beautiful things about Poster is how opinionated it is, which won't be the case if we bundle subgraphs and frontends into the same repo.

**Comment by jjperezaguinaga** [comment]
Awesome, let's do it. Following-up in #24

**Comment by auryn-macmillan** [comment]
To this end, we should also put the subgraph in a separate repo to the front-end. That way it's easier for others to use it to build their own frontends.

**Comment by jjperezaguinaga** [comment]
Indeed, seems like [that's the case already](https://github.com/ETHPoster/subgraph)
