### ISSUE TITLE
Provide support for other networks, discuss options for aggregating contents in a single page

### ISSUE THREAD

**Issue by jjperezaguinaga** [ETHPoster/app#12]

**Comment by auryn-macmillan** [comment]
Yaniv mentioned that subgraphs [cannot pull data from one and other yet](https://twitter.com/yanivgraph/status/1421639746678362115), so I'm not sure if there is a good way to aggregate information from multiple networks without it being a lot of work on the client.

But yeah, ideally it would be great if we could have Poster deployed to just about any EVM compatible network, users could choose where they want to post, and it would all show up in the same app.

**Comment by jjperezaguinaga** [comment]
I had a discussion last friday with @schmidsi about the ability to have a smart contract registry that a subgraph can index to fetch multiple smart contracts, but no option for cross-chain indexing AFAIK.

I agree that the easiest is to deploy a subgraph to any EVM-compatible network. I'll take care of that in #19

**Comment by schmidsi** [comment]
Right. Until we have subgraph-composition implemented, you need to redeploy the subgraph on every network that you want to support. On the client, you can use https://github.com/urigo/graphql-mesh. It makes it quite easy to combine different subgraphs. Please ping me if you have used it. Would love to hear your feedback on it.
